# Generated by Django 4.1.5 on 2023-01-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Praias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descr', models.CharField(max_length=250)),
                ('ref', models.CharField(max_length=10, unique=True)),
                ('bairro', models.CharField(max_length=150)),
                ('coord', models.CharField(max_length=50, unique=True)),
                ('mapa', models.CharField(max_length=500)),
                ('propria', models.BooleanField(default=False)),
                ('atualizado_em', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Relatorios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, unique=True)),
                ('url', models.CharField(max_length=250)),
            ],
        ),
    ]
