# Generated by Django 4.1.5 on 2023-02-02 13:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('praias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relatorios',
            name='verifica',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
